# This is a basic workflow to help you get started with Actions

name: Test issue 4#

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
env:
  TZ: 'Asia/Shanghai'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: create files
        run: |
          mkdir -p project/node_modules/library1/
          mkdir -p project/test/utils/
          echo "some library" > project/node_modules/library1/index.ts
          echo "some test" > project/test/index.spec.ts
          echo "util test" > project/test/utils/util.spec.ts
          echo "src file" > project/index.ts

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.3.3
        with:
          host: ${{ secrets.HOST }}
          port: 22 # optional, default is 22
          privateKey: ${{ secrets.SERVER_KEY }}
          localDir: 'project'
          remoteDir: '/project/'
          exclude: 'node_modules/,**/*.spec.ts'
          excludeMode: 'ignore'
          dryRun: true # optional

