# This is a basic workflow to help you get started with Actions

name: Test issue 15#

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
env:
  TZ: 'Asia/Shanghai'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: create key file
        run: |
          echo "${{ secrets.SERVER_KEY }}" > ./id_rsa
          pwd
          ls

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.4.8
        with:
          host: ${{ secrets.HOST }}
          port: 5190
          privateKey: './id_rsa'
          localDir: './test'
          remoteDir: '/root/test/'
